<?php

return [
    'online' => '線上',
    'offline' => '離線',
    'starting' => '啟動中',
    'stopping' => '停止中',
    'suspended' => 'Suspended',
    'connection-error' => 'Connection Error',
    'transferring' => 'Transferring',
    'installing' => 'Installing',
    'restoring-backup' => 'Restoring Backup',
    'unavailable' => 'Unavailable',
    'status' => '狀態',
    'CPU' => 'CPU',
    'memory' => '記憶體',
    'disk' => '儲存空間',
    'unlimited' => '無限制',
    'start' => '啟動',
    'restart' => '重啟',
    'stop' => '停止',
    'kill' => '終止',
    'forcibly-stop-process' => 'Forcibly Stop Process',
    'continue' => '繼續',
    'forcibly-stopping-alert' => 'Forcibly stopping a server can lead to data corruption.',
    'cpu-usage' => 'CPU Usage',
    'memory-usage' => 'Memory Usage',
    'disk-usage' => 'Disk Usage',
    'inbound-outbound' => 'Inbound / Outbound',
    'low-resources' => 'Low on resources',
    'low-resources-desc' => 'Your server is running low on resources, make sure to upgrade your plan',
    'upgrade-server' => 'Upgrade Server',
    'cancel' => 'Cancel',
    'copied-text' => 'Copied {{text}} to clipboard.',
    'showing' => 'Showing',
    'to' => 'to',
    'of' => 'of',
    'results' => 'results.',
];