<?php

return [
    'online' => '線上',
    'offline' => '離線',
    'starting' => '啟動中',
    'stopping' => '停止中',
    'suspended' => '已停用',
    'connection-error' => '連線錯誤',
    'transferring' => '正在轉移',
    'installing' => '正在安裝',
    'restoring-backup' => '正在還原備份',
    'unavailable' => '不可用',
    'status' => '狀態',
    'CPU' => 'CPU',
    'memory' => '記憶體',
    'disk' => '儲存空間',
    'unlimited' => '無限制',
    'start' => '啟動',
    'restart' => '重啟',
    'stop' => '停止',
    'kill' => '終止',
    'forcibly-stop-process' => '強制終止程序',
    'continue' => '繼續',
    'forcibly-stopping-alert' => '強制停止伺服器可能導致伺服器資料損毀。',
    'cpu-usage' => 'CPU 使用率',
    'memory-usage' => '記憶體使用率',
    'disk-usage' => '硬碟使用率',
    'inbound-outbound' => '輸入／輸出',
    'low-resources' => '資源不足',
    'low-resources-desc' => '你的伺服器正在以低資源量運作，請確保升級方案來保證穩定',
    'upgrade-server' => '升級伺服器',
    'cancel' => '取消',
    'copied-text' => '已複製 {{text}} 到剪貼簿。',
    'showing' => '顯示',
    'to' => '到',
    'of' => '的',
    'results' => '結果。',
];