<?php

return [
    'file-manager' => '檔案管理',
    'search' => '搜尋',
    'delete' => '刪除',
    'move' => '移動',
    'archive' => '封存',
    'unarchive' => '解封存',
    'create-directory' => '建立資料夾',
    'upload' => '上傳',
    'new-file' => '建立新檔案',
    'rename' => '重新命名',
    'permissions' => '權限',
    'copy' => '複製',
    'download' => '下載',
    'update' => '更新',
    'file-mode' => '檔案模式',
    'you-cant-recover' => '當你刪除之後',
    'once-deleted' => '將無法還原內容。',
    'delete-files' => '刪除檔案',
    'are-you-sure' => '你確定你想要刪除',
    'this-is-permanent-action' => '這是個永久性操作且檔案將無法再被還原。',
    'name' => '名稱',
    'size' => '大小',
    'date' => '日期',
    'home' => '家',
    'container' => '容器',
    'is-empty' => '這個資料夾看似乎是空的。',
    'is-limited' => '此資料夾過大，無法在瀏覽器中顯示。將限制輸出前 250 個檔案。',
    'are-upload-click-to-view' => '檔案正在上傳中，點擊查看',
    'cancel-uploads' => '取消上傳',
    'cancel' => '取消',
    'close' => '關閉',
    'create' => '建立',
    'file-name' => '檔案名稱',
    'file-name-description' => '請輸入要儲存的檔案名稱。',
    'directory-will-be-as' => '此資料夾將建立為',
    'rename-description' => '輸入此檔案名稱或資料夾名稱的新名稱和資料夾，相對於目前資料夾位置。',
    'new-location' => '新位置',
    'drag-and-drop' => '拖放檔案來上傳。',

    'edit' => [
        'youre-editing' => '你正在編輯',
        'will-be-exluded' => '檔案。此處列出的任何文件或資料夾將會從備份中排除。萬用字元是支援的，請使用星號。',
        'you-can-negate' => '你可以透過在前面加上驚嘆號來取消之前的規則',
        'save-content' => '儲存內容',
        'create-file' => '建立檔案',
    ],
];